# (c) 2025 Shane D. Shook, PhD - All Rights Reserved

"""
ADVulture — Random Forest Scenario Model
Tests combinatorial control sets and handles interaction effects
that the GNN gradient assumes away. Complements the gradient engine
by predicting non-linear outcomes of deploying multiple controls.
"""

from __future__ import annotations
import logging
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

log = logging.getLogger(__name__)

# Check for SHAP availability (optional dependency for interaction analysis)
try:
    import shap
    SHAP_AVAILABLE = True
except ImportError:
    SHAP_AVAILABLE = False
    log.debug("SHAP not available — interaction detection will use rule-based fallback")


@dataclass
class ScenarioCandidate:
    """A proposed set of control deployments to evaluate."""
    controls: Dict[str, float]
    predicted_tier0_prob: float
    predicted_std: float            # RF uncertainty (tree variance)
    absolute_reduction: float
    pct_reduction: float
    interaction_effects: List[str]  # notable control synergies detected
    confidence: float


@dataclass
class TrainingPoint:
    """One training example: control vector → observed steady-state probability."""
    control_vector: np.ndarray
    tier0_probability: float
    domain_size: int
    esc_count: int
    unconstrained_delegation_count: int
    lpe_surface_score: float


CONTROL_NAMES = [
    "mfa_coverage", "laps_deployed", "edr_coverage", "adcs_hardened",
    "tiered_admin", "smb_signing", "delegation_audit", "dcsync_audited",
    "mcp_scope_restriction", "adfs_claim_review", "aes_enforcement",
    "ntlm_restriction", "sid_filtering", "rbcd_monitoring",
    "local_admin_audit", "agent_content_isolation",
]


class ADScenarioForest:
    """
    Random Forest for scenario testing.

    Trained on (control_vector, environment_features) → π_tier0.
    Key advantage over gradient engine: captures interaction effects.
    Example: MFA + LAPS together suppress PTH more than their individual
    gradients suggest — the RF captures this synergy.

    In production: pre-train on synthetic environments generated by
    running the full Markov analysis across thousands of control
    configurations. Periodically retrain as new observations accumulate.
    """

    def __init__(self, n_estimators: int = 300, max_depth: int = 8):
        self.model = RandomForestRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=-1,
        )
        self.trained = False
        self.feature_names = CONTROL_NAMES + [
            "domain_size_log", "esc_count", "unconstrained_deleg_count",
            "lpe_surface_score",
        ]
        self._training_X: Optional[np.ndarray] = None  # For SHAP background
        self._shap_explainer = None
        self._shap_interactions: Optional[np.ndarray] = None

    def train(self, training_points: List[TrainingPoint]) -> float:
        """
        Train the RF model. Returns cross-validated R² score.
        
        Note: RF is split-based and invariant to monotonic feature transformations,
        so we don't use StandardScaler here (it adds no benefit for tree models).
        """
        if len(training_points) < 20:
            log.warning("Insufficient training data (%d points) — RF predictions unreliable",
                        len(training_points))

        X = np.array([self._featurise(t) for t in training_points])
        y = np.array([t.tier0_probability for t in training_points])

        self.model.fit(X, y)
        self.trained = True
        self._training_X = X  # Keep for SHAP background
        
        # Compute SHAP interactions if available
        self._compute_shap_interactions(X)

        if len(training_points) >= 10:
            cv_scores = cross_val_score(self.model, X, y, cv=min(5, len(training_points)))
            r2 = float(cv_scores.mean())
            log.info("RF trained. CV R²=%.3f ± %.3f", r2, cv_scores.std())
            return r2
        return 0.0
    
    def _compute_shap_interactions(self, X: np.ndarray) -> None:
        """Compute SHAP interaction values to detect control synergies."""
        if not SHAP_AVAILABLE:
            return
        
        try:
            # Use a sample of background data for efficiency
            n_background = min(100, len(X))
            background = X[np.random.choice(len(X), n_background, replace=False)]
            
            self._shap_explainer = shap.TreeExplainer(self.model, background)
            
            # Compute interaction values on a sample
            n_interactions = min(50, len(X))
            sample = X[np.random.choice(len(X), n_interactions, replace=False)]
            self._shap_interactions = self._shap_explainer.shap_interaction_values(sample)
            
            log.info("SHAP interaction values computed for %d control pairs", 
                     len(CONTROL_NAMES) * (len(CONTROL_NAMES) - 1) // 2)
        except Exception as e:
            log.debug("SHAP interaction computation failed: %s", e)
            self._shap_interactions = None

    def generate_synthetic_training_data(
        self,
        markov_runner,
        n_samples: int = 2000,  # Increased from 500 for better interaction coverage
        env_features: Optional[Dict] = None,
    ) -> List[TrainingPoint]:
        """
        Generate training data by sampling random control configurations
        and computing their actual Markov steady-state probabilities.
        This is the ground-truth training signal for the RF.
        
        With 16 controls and potential pairwise interactions, we need
        sufficient samples (>=2000) to capture three-way interactions
        reliably.
        """
        import torch
        training_points = []
        env = env_features or {}

        log.info("Generating %d synthetic training points...", n_samples)
        
        for i in range(n_samples):
            # Use bimodal beta distribution that better matches real deployments
            # Controls are typically either deployed (>=0.7) or not (<=0.2)
            if np.random.random() < 0.5:
                # Low deployment region
                a, b = 0.3, 2.0
            else:
                # High deployment region
                a, b = 2.0, 0.3
            
            controls = {
                ctrl: float(np.random.beta(a=a, b=b))
                for ctrl in CONTROL_NAMES
            }

            # Force some boundary cases for better edge learning
            if i < n_samples // 10:
                for ctrl in CONTROL_NAMES:
                    controls[ctrl] = float(np.random.choice([0.0, 0.1, 0.9, 1.0]))
            
            # Generate some focused interaction samples
            # (specific control pairs at high values together)
            elif i < n_samples // 5:
                pair = np.random.choice(CONTROL_NAMES, size=2, replace=False)
                for ctrl in pair:
                    controls[ctrl] = float(np.random.uniform(0.8, 1.0))

            # Compute actual Markov result for this control set
            try:
                result = markov_runner(controls)
                training_points.append(TrainingPoint(
                    control_vector=np.array([controls[c] for c in CONTROL_NAMES]),
                    tier0_probability=result.tier0_probability,
                    domain_size=env.get("domain_size", 500),
                    esc_count=env.get("esc_count", 0),
                    unconstrained_delegation_count=env.get("unconstrained_count", 0),
                    lpe_surface_score=env.get("lpe_surface_score", 0.5),
                ))
            except Exception as e:
                log.debug("Skipping point %d: %s", i, e)

        log.info("Generated %d training points", len(training_points))
        return training_points

    def predict(
        self,
        proposed_controls: Dict[str, float],
        env_features: Optional[Dict] = None,
        baseline_controls: Optional[Dict[str, float]] = None,
        baseline_prob: float = 0.5,
    ) -> ScenarioCandidate:
        """
        Predict steady-state Tier0 probability for a proposed control set.
        Returns prediction with uncertainty estimate from tree variance.
        """
        if not self.trained:
            log.warning("RF not trained — returning heuristic estimate")
            return self._heuristic_estimate(proposed_controls, baseline_prob)

        merged = dict(baseline_controls or {})
        merged.update(proposed_controls)

        env = env_features or {}
        features = np.array([[
            *[merged.get(c, 0.5) for c in CONTROL_NAMES],
            np.log1p(env.get("domain_size", 500)),
            env.get("esc_count", 0),
            env.get("unconstrained_count", 0),
            env.get("lpe_surface_score", 0.5),
        ]])

        # Per-tree predictions for uncertainty
        tree_preds = np.array([
            tree.predict(features)[0]
            for tree in self.model.estimators_
        ])
        predicted = float(tree_preds.mean())
        predicted_std = float(tree_preds.std())
        predicted = max(0.0, min(1.0, predicted))

        reduction = baseline_prob - predicted
        pct = (reduction / max(baseline_prob, 0.001)) * 100

        # Detect interactions (SHAP-based if available, rule-based fallback)
        interactions = self._detect_interactions(proposed_controls, merged, features)
        
        # Calibrated confidence based on out-of-distribution detection
        # Higher std relative to typical training variance → lower confidence
        confidence = self._compute_confidence(predicted_std, features)

        return ScenarioCandidate(
            controls=proposed_controls,
            predicted_tier0_prob=round(predicted, 4),
            predicted_std=round(predicted_std, 4),
            absolute_reduction=round(reduction, 4),
            pct_reduction=round(pct, 1),
            interaction_effects=interactions,
            confidence=round(confidence, 3),
        )
    
    def _compute_confidence(self, predicted_std: float, features: np.ndarray) -> float:
        """
        Compute calibrated confidence score based on prediction variance
        and distance from training distribution.
        """
        if self._training_X is None:
            return max(0.0, 1.0 - predicted_std * 3)
        
        # Compute distance to nearest training point
        dists = np.linalg.norm(self._training_X - features, axis=1)
        min_dist = float(dists.min())
        
        # Typical training data spread
        training_spread = float(np.std(dists))
        
        # Confidence decreases with distance and std
        dist_factor = 1.0 / (1.0 + min_dist / max(training_spread, 0.1))
        std_factor = 1.0 / (1.0 + predicted_std * 2)
        
        return max(0.0, min(1.0, dist_factor * std_factor))

    def top_scenarios(
        self,
        current_controls: Dict[str, float],
        baseline_prob: float,
        budget: int = 3,
        env_features: Optional[Dict] = None,
        n_candidates: int = 200,
    ) -> List[ScenarioCandidate]:
        """
        Search for the best combination of `budget` control improvements.
        
        Uses a hybrid approach:
        1. Greedy hill-climbing: iteratively add the best single control
        2. Random exploration: sample diverse combinations
        3. Feature importance-weighted sampling: focus on high-impact controls
        """
        candidates = []
        improvable = [
            c for c in CONTROL_NAMES
            if current_controls.get(c, 0) < 0.9
        ]
        
        if not improvable:
            return []
        
        # Get feature importances to weight sampling
        importances = dict(self.feature_importances()) if self.trained else {}
        weights = np.array([importances.get(c, 1.0) for c in improvable])
        weights = weights / weights.sum()
        
        # --- Strategy 1: Greedy hill-climbing ---
        for _ in range(3):  # Multiple greedy runs with randomization
            greedy_controls = {}
            remaining_budget = budget
            
            while remaining_budget > 0 and improvable:
                best_ctrl = None
                best_reduction = -float('inf')
                
                for ctrl in improvable:
                    if ctrl in greedy_controls:
                        continue
                    test_proposal = dict(greedy_controls)
                    test_proposal[ctrl] = min(1.0, current_controls.get(ctrl, 0) + 0.7)
                    
                    candidate = self.predict(
                        test_proposal, env_features, current_controls, baseline_prob
                    )
                    if candidate.absolute_reduction > best_reduction:
                        best_reduction = candidate.absolute_reduction
                        best_ctrl = ctrl
                
                if best_ctrl:
                    improvement = np.random.uniform(0.5, 0.8)  # Add some randomness
                    greedy_controls[best_ctrl] = min(1.0, current_controls.get(best_ctrl, 0) + improvement)
                    remaining_budget -= 1
                else:
                    break
            
            if greedy_controls:
                candidates.append(self.predict(
                    greedy_controls, env_features, current_controls, baseline_prob
                ))
        
        # --- Strategy 2: Random exploration with importance weighting ---
        for _ in range(n_candidates - len(candidates)):
            # Sample controls with importance-based probability
            n_select = min(budget, len(improvable))
            selected = np.random.choice(
                improvable,
                size=n_select,
                replace=False,
                p=weights,
            )
            proposed = {
                ctrl: min(1.0, current_controls.get(ctrl, 0) + np.random.uniform(0.3, 0.8))
                for ctrl in selected
            }
            candidate = self.predict(
                proposed, env_features, current_controls, baseline_prob
            )
            candidates.append(candidate)
        
        # --- Strategy 3: Known synergistic pairs ---
        synergy_pairs = [
            ("mfa_coverage", "laps_deployed"),
            ("adcs_hardened", "mfa_coverage"),
            ("edr_coverage", "laps_deployed"),
            ("tiered_admin", "delegation_audit"),
            ("mcp_scope_restriction", "agent_content_isolation"),
        ]
        for ctrl1, ctrl2 in synergy_pairs:
            if ctrl1 in improvable and ctrl2 in improvable:
                proposed = {
                    ctrl1: min(1.0, current_controls.get(ctrl1, 0) + 0.7),
                    ctrl2: min(1.0, current_controls.get(ctrl2, 0) + 0.7),
                }
                if budget > 2:
                    # Add a third control with highest importance
                    remaining = [c for c in improvable if c not in proposed]
                    if remaining:
                        third = max(remaining, key=lambda c: importances.get(c, 0))
                        proposed[third] = min(1.0, current_controls.get(third, 0) + 0.5)
                
                candidates.append(self.predict(
                    proposed, env_features, current_controls, baseline_prob
                ))

        # Deduplicate and sort
        seen = set()
        unique_candidates = []
        for c in sorted(candidates, key=lambda x: x.absolute_reduction, reverse=True):
            key = tuple(sorted(c.controls.items()))
            if key not in seen:
                seen.add(key)
                unique_candidates.append(c)
        
        return unique_candidates[:10]

    def feature_importances(self) -> List[Tuple[str, float]]:
        """Return feature importances ranked by contribution."""
        if not self.trained:
            return []
        importances = self.model.feature_importances_
        return sorted(
            zip(self.feature_names, importances),
            key=lambda x: x[1],
            reverse=True,
        )

    def _featurise(self, point: TrainingPoint) -> np.ndarray:
        return np.array([
            *point.control_vector,
            np.log1p(point.domain_size),
            point.esc_count,
            point.unconstrained_delegation_count,
            point.lpe_surface_score,
        ])

    def _detect_interactions(
        self, proposed: Dict[str, float], merged: Dict[str, float], 
        features: Optional[np.ndarray] = None
    ) -> List[str]:
        """
        Identify synergistic control combinations in the proposal.
        
        Uses SHAP interaction values when available to surface data-driven
        interactions. Falls back to domain knowledge rules.
        """
        synergies = []
        m = merged

        # Try SHAP-based interaction detection first
        if features is not None and SHAP_AVAILABLE and self._shap_interactions is not None:
            shap_synergies = self._shap_interaction_analysis(proposed, features)
            synergies.extend(shap_synergies)
        
        # Always include domain knowledge rules (complementary to SHAP)
        if m.get("mfa_coverage", 0) > 0.8 and m.get("laps_deployed", 0) > 0.8:
            synergies.append(
                "MFA + LAPS synergy: combined suppression of credential theft chains "
                "exceeds sum of individual controls"
            )
        if m.get("adcs_hardened", 0) > 0.8 and m.get("mfa_coverage", 0) > 0.8:
            synergies.append(
                "ADCS hardening + MFA: certificate-based auth bypasses MFA — "
                "both controls required for full suppression of ESC1/ESC2 paths"
            )
        if m.get("edr_coverage", 0) > 0.8 and m.get("laps_deployed", 0) > 0.8:
            synergies.append(
                "EDR + LAPS synergy: EDR detects LPE attempt; "
                "LAPS prevents harvest of reusable local admin credentials"
            )
        if m.get("tiered_admin", 0) > 0.7 and m.get("delegation_audit", 0) > 0.7:
            synergies.append(
                "Tiered admin + delegation audit: Tier 0 isolation "
                "plus delegation cleanup removes the most common DA escalation paths"
            )
        if m.get("mcp_scope_restriction", 0) > 0.8 and m.get("agent_content_isolation", 0) > 0.8:
            synergies.append(
                "MCP scope + content isolation: combined AI agent surface reduction — "
                "scope limits blast radius; isolation prevents injection weaponisation"
            )
        
        # Deduplicate
        return list(dict.fromkeys(synergies))
    
    def _shap_interaction_analysis(
        self, proposed: Dict[str, float], features: np.ndarray
    ) -> List[str]:
        """
        Analyze SHAP interaction values for the proposed control set.
        Returns explanations of detected interaction effects.
        """
        if self._shap_interactions is None:
            return []
        
        synergies = []
        
        try:
            # Get indices of proposed controls
            proposed_indices = [
                CONTROL_NAMES.index(ctrl) 
                for ctrl in proposed.keys() 
                if ctrl in CONTROL_NAMES
            ]
            
            if len(proposed_indices) < 2:
                return []
            
            # Average interaction matrix across samples
            # _shap_interactions shape: [n_samples, n_features, n_features]
            avg_interactions = np.abs(self._shap_interactions).mean(axis=0)
            
            # Check interaction strength between proposed controls
            for i, idx1 in enumerate(proposed_indices):
                for idx2 in proposed_indices[i+1:]:
                    interaction_strength = avg_interactions[idx1, idx2]
                    
                    # If interaction is significant (top 10% of all interactions)
                    threshold = np.percentile(avg_interactions, 90)
                    if interaction_strength > threshold:
                        ctrl1 = CONTROL_NAMES[idx1]
                        ctrl2 = CONTROL_NAMES[idx2]
                        synergies.append(
                            f"SHAP-detected synergy: {ctrl1} + {ctrl2} "
                            f"(interaction strength: {interaction_strength:.3f})"
                        )
        except Exception as e:
            log.debug("SHAP interaction analysis failed: %s", e)
        
        return synergies
    
    def get_top_interactions(self, n: int = 10) -> List[Tuple[str, str, float]]:
        """
        Return the top N strongest control interactions learned by the model.
        Requires SHAP to be available and model to be trained.
        """
        if self._shap_interactions is None:
            return []
        
        try:
            avg_interactions = np.abs(self._shap_interactions).mean(axis=0)
            
            # Get all unique pairs
            n_controls = len(CONTROL_NAMES)
            pairs = []
            for i in range(n_controls):
                for j in range(i + 1, n_controls):
                    pairs.append((CONTROL_NAMES[i], CONTROL_NAMES[j], avg_interactions[i, j]))
            
            # Sort by interaction strength
            pairs.sort(key=lambda x: x[2], reverse=True)
            return pairs[:n]
        except Exception as e:
            log.debug("Failed to get top interactions: %s", e)
            return []

    def _heuristic_estimate(
        self, proposed: Dict[str, float], baseline: float
    ) -> ScenarioCandidate:
        """Fallback when RF is not trained — linear gradient approximation."""
        weights = {
            "mfa_coverage": 0.12, "laps_deployed": 0.08, "edr_coverage": 0.15,
            "adcs_hardened": 0.14, "tiered_admin": 0.10, "smb_signing": 0.06,
            "delegation_audit": 0.09, "dcsync_audited": 0.08,
            "mcp_scope_restriction": 0.05, "adfs_claim_review": 0.06,
        }
        reduction = sum(
            weights.get(ctrl, 0.04) * val
            for ctrl, val in proposed.items()
        )
        predicted = max(0.0, baseline - reduction * baseline)
        return ScenarioCandidate(
            controls=proposed,
            predicted_tier0_prob=round(predicted, 4),
            predicted_std=0.1,
            absolute_reduction=round(baseline - predicted, 4),
            pct_reduction=round((baseline - predicted) / max(baseline, 0.001) * 100, 1),
            interaction_effects=[],
            confidence=0.5,
        )
