# (c) 2025 Shane D. Shook, PhD - All Rights Reserved

"""
ADVulture — Random Forest Scenario Model
Tests combinatorial control sets and handles interaction effects
that the GNN gradient assumes away. Complements the gradient engine
by predicting non-linear outcomes of deploying multiple controls.
"""

from __future__ import annotations
import logging
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

log = logging.getLogger(__name__)


@dataclass
class ScenarioCandidate:
    """A proposed set of control deployments to evaluate."""
    controls: Dict[str, float]
    predicted_tier0_prob: float
    predicted_std: float            # RF uncertainty (tree variance)
    absolute_reduction: float
    pct_reduction: float
    interaction_effects: List[str]  # notable control synergies detected
    confidence: float


@dataclass
class TrainingPoint:
    """One training example: control vector → observed steady-state probability."""
    control_vector: np.ndarray
    tier0_probability: float
    domain_size: int
    esc_count: int
    unconstrained_delegation_count: int
    lpe_surface_score: float


CONTROL_NAMES = [
    "mfa_coverage", "laps_deployed", "edr_coverage", "adcs_hardened",
    "tiered_admin", "smb_signing", "delegation_audit", "dcsync_audited",
    "mcp_scope_restriction", "adfs_claim_review", "aes_enforcement",
    "ntlm_restriction", "sid_filtering", "rbcd_monitoring",
    "local_admin_audit", "agent_content_isolation",
]


class ADScenarioForest:
    """
    Random Forest for scenario testing.

    Trained on (control_vector, environment_features) → π_tier0.
    Key advantage over gradient engine: captures interaction effects.
    Example: MFA + LAPS together suppress PTH more than their individual
    gradients suggest — the RF captures this synergy.

    In production: pre-train on synthetic environments generated by
    running the full Markov analysis across thousands of control
    configurations. Periodically retrain as new observations accumulate.
    """

    def __init__(self, n_estimators: int = 300, max_depth: int = 8):
        self.model = RandomForestRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=-1,
        )
        self.scaler = StandardScaler()
        self.trained = False
        self.feature_names = CONTROL_NAMES + [
            "domain_size_log", "esc_count", "unconstrained_deleg_count",
            "lpe_surface_score",
        ]

    def train(self, training_points: List[TrainingPoint]) -> float:
        """
        Train the RF model. Returns cross-validated R² score.
        """
        if len(training_points) < 20:
            log.warning("Insufficient training data (%d points) — RF predictions unreliable",
                        len(training_points))

        X = np.array([self._featurise(t) for t in training_points])
        y = np.array([t.tier0_probability for t in training_points])

        X_scaled = self.scaler.fit_transform(X)
        self.model.fit(X_scaled, y)
        self.trained = True

        if len(training_points) >= 10:
            cv_scores = cross_val_score(self.model, X_scaled, y, cv=min(5, len(training_points)))
            r2 = float(cv_scores.mean())
            log.info("RF trained. CV R²=%.3f ± %.3f", r2, cv_scores.std())
            return r2
        return 0.0

    def generate_synthetic_training_data(
        self,
        markov_runner,
        n_samples: int = 500,
        env_features: Optional[Dict] = None,
    ) -> List[TrainingPoint]:
        """
        Generate training data by sampling random control configurations
        and computing their actual Markov steady-state probabilities.
        This is the ground-truth training signal for the RF.
        """
        import torch
        training_points = []
        env = env_features or {}

        log.info("Generating %d synthetic training points...", n_samples)
        for i in range(n_samples):
            # Sample random control deployment levels
            controls = {
                ctrl: float(np.random.beta(a=1.5, b=1.5))  # beta skew toward middle
                for ctrl in CONTROL_NAMES
            }

            # Force some extreme cases for better boundary learning
            if i < n_samples // 10:
                for ctrl in CONTROL_NAMES:
                    controls[ctrl] = float(np.random.choice([0.0, 0.1, 0.9, 1.0]))

            # Compute actual Markov result for this control set
            try:
                result = markov_runner(controls)
                training_points.append(TrainingPoint(
                    control_vector=np.array([controls[c] for c in CONTROL_NAMES]),
                    tier0_probability=result.tier0_probability,
                    domain_size=env.get("domain_size", 500),
                    esc_count=env.get("esc_count", 0),
                    unconstrained_delegation_count=env.get("unconstrained_count", 0),
                    lpe_surface_score=env.get("lpe_surface_score", 0.5),
                ))
            except Exception as e:
                log.debug("Skipping point %d: %s", i, e)

        log.info("Generated %d training points", len(training_points))
        return training_points

    def predict(
        self,
        proposed_controls: Dict[str, float],
        env_features: Optional[Dict] = None,
        baseline_controls: Optional[Dict[str, float]] = None,
        baseline_prob: float = 0.5,
    ) -> ScenarioCandidate:
        """
        Predict steady-state Tier0 probability for a proposed control set.
        Returns prediction with uncertainty estimate from tree variance.
        """
        if not self.trained:
            log.warning("RF not trained — returning heuristic estimate")
            return self._heuristic_estimate(proposed_controls, baseline_prob)

        merged = dict(baseline_controls or {})
        merged.update(proposed_controls)

        env = env_features or {}
        features = np.array([[
            *[merged.get(c, 0.5) for c in CONTROL_NAMES],
            np.log1p(env.get("domain_size", 500)),
            env.get("esc_count", 0),
            env.get("unconstrained_count", 0),
            env.get("lpe_surface_score", 0.5),
        ]])

        X_scaled = self.scaler.transform(features)

        # Per-tree predictions for uncertainty
        tree_preds = np.array([
            tree.predict(X_scaled)[0]
            for tree in self.model.estimators_
        ])
        predicted = float(tree_preds.mean())
        predicted_std = float(tree_preds.std())
        predicted = max(0.0, min(1.0, predicted))

        reduction = baseline_prob - predicted
        pct = (reduction / max(baseline_prob, 0.001)) * 100

        interactions = self._detect_interactions(proposed_controls, merged)

        return ScenarioCandidate(
            controls=proposed_controls,
            predicted_tier0_prob=round(predicted, 4),
            predicted_std=round(predicted_std, 4),
            absolute_reduction=round(reduction, 4),
            pct_reduction=round(pct, 1),
            interaction_effects=interactions,
            confidence=max(0.0, 1.0 - predicted_std * 5),
        )

    def top_scenarios(
        self,
        current_controls: Dict[str, float],
        baseline_prob: float,
        budget: int = 3,
        env_features: Optional[Dict] = None,
        n_candidates: int = 200,
    ) -> List[ScenarioCandidate]:
        """
        Search for the best combination of `budget` control improvements.
        Uses random sampling to explore the combinatorial space.
        """
        candidates = []

        for _ in range(n_candidates):
            # Sample `budget` controls to improve
            improvable = [
                c for c in CONTROL_NAMES
                if current_controls.get(c, 0) < 0.9
            ]
            if not improvable:
                break
            selected = np.random.choice(
                improvable,
                size=min(budget, len(improvable)),
                replace=False,
            )
            proposed = {
                ctrl: min(1.0, current_controls.get(ctrl, 0) + np.random.uniform(0.3, 0.7))
                for ctrl in selected
            }
            candidate = self.predict(
                proposed, env_features, current_controls, baseline_prob
            )
            candidates.append(candidate)

        candidates.sort(key=lambda c: c.absolute_reduction, reverse=True)
        return candidates[:10]

    def feature_importances(self) -> List[Tuple[str, float]]:
        """Return feature importances ranked by contribution."""
        if not self.trained:
            return []
        importances = self.model.feature_importances_
        return sorted(
            zip(self.feature_names, importances),
            key=lambda x: x[1],
            reverse=True,
        )

    def _featurise(self, point: TrainingPoint) -> np.ndarray:
        return np.array([
            *point.control_vector,
            np.log1p(point.domain_size),
            point.esc_count,
            point.unconstrained_delegation_count,
            point.lpe_surface_score,
        ])

    def _detect_interactions(
        self, proposed: Dict[str, float], merged: Dict[str, float]
    ) -> List[str]:
        """
        Identify known synergistic control combinations in the proposal.
        """
        synergies = []
        m = merged

        if m.get("mfa_coverage", 0) > 0.8 and m.get("laps_deployed", 0) > 0.8:
            synergies.append(
                "MFA + LAPS synergy: combined suppression of credential theft chains "
                "exceeds sum of individual controls"
            )
        if m.get("adcs_hardened", 0) > 0.8 and m.get("mfa_coverage", 0) > 0.8:
            synergies.append(
                "ADCS hardening + MFA: certificate-based auth bypasses MFA — "
                "both controls required for full suppression of ESC1/ESC2 paths"
            )
        if m.get("edr_coverage", 0) > 0.8 and m.get("laps_deployed", 0) > 0.8:
            synergies.append(
                "EDR + LAPS synergy: EDR detects LPE attempt; "
                "LAPS prevents harvest of reusable local admin credentials"
            )
        if m.get("tiered_admin", 0) > 0.7 and m.get("delegation_audit", 0) > 0.7:
            synergies.append(
                "Tiered admin + delegation audit: Tier 0 isolation "
                "plus delegation cleanup removes the most common DA escalation paths"
            )
        if m.get("mcp_scope_restriction", 0) > 0.8 and m.get("agent_content_isolation", 0) > 0.8:
            synergies.append(
                "MCP scope + content isolation: combined AI agent surface reduction — "
                "scope limits blast radius; isolation prevents injection weaponisation"
            )
        return synergies

    def _heuristic_estimate(
        self, proposed: Dict[str, float], baseline: float
    ) -> ScenarioCandidate:
        """Fallback when RF is not trained — linear gradient approximation."""
        weights = {
            "mfa_coverage": 0.12, "laps_deployed": 0.08, "edr_coverage": 0.15,
            "adcs_hardened": 0.14, "tiered_admin": 0.10, "smb_signing": 0.06,
            "delegation_audit": 0.09, "dcsync_audited": 0.08,
            "mcp_scope_restriction": 0.05, "adfs_claim_review": 0.06,
        }
        reduction = sum(
            weights.get(ctrl, 0.04) * val
            for ctrl, val in proposed.items()
        )
        predicted = max(0.0, baseline - reduction * baseline)
        return ScenarioCandidate(
            controls=proposed,
            predicted_tier0_prob=round(predicted, 4),
            predicted_std=0.1,
            absolute_reduction=round(baseline - predicted, 4),
            pct_reduction=round((baseline - predicted) / max(baseline, 0.001) * 100, 1),
            interaction_effects=[],
            confidence=0.5,
        )
